run_docker:
  stage: build
  image: alpine #docker:24.0.5
  #services:
  #  - docker:24.0.5-dind
  script:
    - echo "Mocoloco461 - testing docker"
    - echo $POSTGRES_USER
    - echo ${POSTGRES_USER}