stages:
  - build_and_test
  - buid_and_run
  - push


test_via_django_tests:
  stage: build_and_test
  image: docker:20.10-dind
  services:
    - docker:20.10-dind
  script:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    - docker compose -f docker-compose-test.yaml up --build --exit-code-from app-locallibary-unitest
    # - docker save -o locallibary.tar locallibary:latest
    # build test puhs all in one

    - export IMAGE_TAG=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$CI_COMMIT_REF_SLUG" | tr '[:upper:]' '[:lower:]')
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    # - docker load -i locallibary.tar
    - docker tag locallibary:latest $IMAGE_TAG
    - docker push $IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "prodtest"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_MESSAGE =~ /^build:/





    
  # artifacts:
  #   paths:
  #     - locallibary.tar
  #   expire_in: '1 hour'


# run_the_app:
#   stage: buid_and_run
#   image: alpine
#   script:
#     - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#     - docker load -i locallibary.tar
#     - docker compose up -d 
#     # none prodactions thing !!! need to use health of the continer!!!
#     - sleep 20
#     - curl localhost:6060 && echo $?

#   dependencies:
#     - test_via_django_tests


# here i pushing the last image

# push_image:
#   image: docker:24.0.5-cli
#   stage: push
#   services:
#     - docker:24.0.5-dind
    
#   script:
#     - export IMAGE_TAG=$(echo "$CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME:$CI_COMMIT_REF_SLUG" | tr '[:upper:]' '[:lower:]')
#     - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
#     - docker load -i locallibary.tar
#     - docker tag locallibary:latest $IMAGE_TAG
#     - docker push $IMAGE_TAG

#   dependencies:
#     - test_via_django_tests
