stages:
  - build
  - push


run_docker:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - DATABASE_URL=postgres://${POSTGRES_USER_TEST}:${POSTGRES_PASSWORD_TEST}@db:5432/${POSTGRES_DB_TEST}
    - docker compose -f docker-compose-test.yaml up --build --exit-code-from app_libary
    - docker save -o locallibary.tar locallibary:latest
    - echo $?
    - ls
  artifacts:
    paths:
      - app-locallibary.tar
    expire_in: '1 hour'


push_image:
  stage: push
  image: alpine
  script:
    - ls
  dependencies:
    - run_docker
