services:
  db:
    container_name: db-locallibary
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app-libary:
    #build: .
    container_name: app-locallibary
    image: registry.gitlab.com/mocoloco461/django_locallibary/locallibary
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py test
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "6060:8000"
    depends_on:
      - db
    restart: "no"
    

volumes:
  pgdata:
