services:
  app-locallibary-unitest:
    #build: .
    container_name: app-locallibary-unitest
    image: locallibary:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python3 manage.py test
      "
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}
    #   DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "6060:8000"
    restart: no