{{- with index .Values "app-deployment"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app.kubernetes.io/{{.metadata.labels.key}}: {{.metadata.labels.volume}}
spec:
  replicas: {{.spec.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/{{.spec.selector.matchLabels.key}}: {{.spec.selector.matchLabels.volume}}
  template:
    metadata:
      labels:
        app.kubernetes.io/{{.spec.template.metadata.labels.key}}: {{.spec.template.metadata.labels.volume}}
    spec:
    
      initContainers:
        {{- range .spec.template.spec.initContainers }}    
        - name: {{.name}}
          image: {{.image}}
          command:
            {{- toYaml .command | nindent 10}}
          env:
            {{- toYaml .env | nindent 10}}
        {{- end}}   
      containers:
          {{- range .spec.template.spec.containers }}
      - name: {{.name}}
        image: {{.image}}        
        command:
          {{ toYaml .command | nindent 10 }}
        args:
          {{- toYaml .args | nindent 10 }}
        ports:
          {{- toYaml .ports | nindent 10}}
        env: 
          {{- toYaml .env | nindent 10}}
      {{- end}}    
{{- end}}