apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app.kubernetes.io/{{.Values.metadata.labels.key}}: {{.Values.metadata.labels.volume}}
spec:
  replicas: {{.Values.spec.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/{{.Values.spec.selector.machLabels.key}}: {{.Values.spec.selector.machLabels.volume}}
  template:
    metadata:
      labels:
        app.kubernetes.io/{{.Values.template.metadata.labels.key}}: {{.Values.template.metadata.labels.volume}}
    spec:

      {{- with.Values.spec.template.spec.initContiners }}    
      initContainers:
      - name: {{.name}}
        image: {{.image}}
        command: {{.command}}
        {{- end}}
        env:
        {{- range .Values.spec.template.spec.initContainers.env }}
        - name: {{.name}}
          valueFrom: 
            secretKeyRef: 
              name: {{.valueFrom.secretKeyRef.name}}
              key: {{.valueFrom.secretKeyRef.key}}
        {{- end}}
              
      {{- with.Values.spec.template.spec.containers }}
      containers:
      - name: {{.name}}
        image: {{.image}}        
        command: {{.command}}
        args:
          - {{.args}}
        ports:
        - containerPort: {{$.Values.spec.template.spec.containers.ports.containerPort}}
        
        env:
          - name: DATABASE_URL
            valueFrom: 
              secretKeyRef:
                name: env
                key: DATABASE_URL

          - name: DJANGO_SECRET_KEY
            valueFrom: 
              secretKeyRef:
                name: env
                key: DJANGO_SECRET_KEY
            