apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service-pvc.metadata.name }}
spec:
  accessModes:
    - {{ .Values.service-pvc.spec.accessModes }}
  resources: 
    requests:
      storage: {{ .Values.service-pvc.spec.resources.requests.storage }}