apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ (index .Values "service-pvc").metadata.name }}
spec:
  accessModes:
    - {{ (index .Values "service-pvc").spec.accessModes }}
  resources: 
    requests:
        storage: {{ (index .Values "service-pvc").spec.resources.requests.storage }}