apiVersion: networking.k3s.io/v1
kind: Ingress
metadata:
  name: locallibary-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
    paths:
    - paths: /
      pathType: Prefix
      backend:
        service:
          name: locallibary
          port:
            number: 80