apiVersion: v1
kind: Secret
metadata:
  name: env
  namespace: default
type: Opaque
stringData:  # החלפנו מ-data ל-stringData
  POSTGRES_DB: locallibrary
  POSTGRES_USER: root
  POSTGRES_PASSWORD: "aCYpomL8k*rE4q2pRyiFsnaG"
  DATABASE_URL: "postgresql://root:aCYpomL8k*rE4q2pRyiFsnaG@db:5432/locallibrary"
  DJANGO_SECRET_KEY: "3it^zhra&=gd*4*b2_%y#&j@1=xdfku*800iht*ZK93slffA2!"
  DJANGO_DEBUG: "False" g