# Generated by Django 4.2.25 on 2025-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="idx",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
