# Generated by Django 4.2.25 on 2025-10-26 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_bookinstance_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookinstance",
            name="idx",
        ),
    ]
