# Generated by Django 4.2.25 on 2025-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_bookinstance_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="idx",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
