---
# Source: helm/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: env
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: locallibrary 
  POSTGRES_USER: root
  POSTGRES_PASSWORD: aCYpomL8k*rE4q2pRyiFsnaG
  DATABASE_URL: postgresql://root:aCYpomL8k*rE4q2pRyiFsnaG@postgres:5432/locallibrary
  DJANGO_SECRET_KEY: 3it^zhra&=gd*4*b2_%y#&j@1=xdfku*800iht*ZK93slffA2!
  DJANGO_DEBUG: "False"
---
# Source: helm/templates/pgdata-pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
        storage: 10Gi
---
# Source: helm/templates/app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: locallibary  
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: locallibary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
# Source: helm/templates/app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres  
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/db: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
# Source: helm/templates/app-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app.kubernetes.io/locallibary: locallibary
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/locallibary: locallibary
  template:
    metadata:
      labels:
        app.kubernetes.io/locallibary: locallibary
    spec:
    
      initContainers:    
        - name: db-migrate
          image: registry.gitlab.com/mocoloco461/django_locallibary/locallibary:prodtest
          command:
          - python
          - manage.py
          - migrate
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: env
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: DJANGO_SECRET_KEY
                name: env   
      containers:
      - name: locallibary
        image: registry.gitlab.com/mocoloco461/django_locallibary/locallibary:prodtest        
        command:
          
          - /bin/bash
          - -c
        args:
          - "python manage.py collectstatic --no-input && gunicorn locallibary.wsgi:application
            --bind 0.0.0.0:8000 \n"
        ports:
          - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: env
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: DJANGO_SECRET_KEY
                name: env
---
# Source: helm/templates/pgdata-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
  labels:
    app.kubernetes.io/postgres: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/postgres: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/postgres: postgres
    spec:
    
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/
          name: postgres-volume
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: env
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: env
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: env

      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# Source: helm/templates/ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: locallibary-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:        
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: locallibary
            port:
              number: 80
